# Generated by Django 6.0.4 on 2026-05-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.IntegerField(db_index=True)),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=3, max_digits=6)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('opis_truckstop_id', 'truckstop_name', 'address', 'city', 'state', 'rack_id'), name='uniq_truckstop_identity')],
            },
        ),
    ]
